theme = "hyde"
baseURL = "/"
languageCode = "en-us"
title = "Catfish"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
    
[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    title = "Tiger's home"
	  description = "R is the brush, math is the pigment, nature is the scenery, and science is the picture."
	  themeColor = "theme-base-0d"
	  dateformat = "2006年1月2日"
	  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Archives"
    weight = 2
    identifier = "archives"
    url = "/post/"
[[menu.main]]
    name = "Categories"
    identifier = "categories"
    weight = 3
    url = "/categories/"
[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 4
    url = "/resume/"
[[menu.main]]
    name = "GitHub"
    weight = 5
    url = "https://github.com/ctfysh"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
