---
title: 收益率悖论
comments: yes
date: '2023-01-14'
layout: post
published: yes
slug: return rate paradox
categories:
  - R
  - finance
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  cache = FALSE,
  message = FALSE,
  warning = FALSE
)
```

# 1 基本原理

假设第$i$期（$i=1,\,2,\,\cdots$）投入资金为$x_i$，期末后总的资金为$y_i$，那么第$i$期的**当期收益率**为

$$
r_i=\dfrac{y_i-x_i-y_{i-1}}{x_i+y_{i-1}}
$$

连续投资$n$期，**总收益率**$R_n$为

$$
R_n=(1+r_1)(1+r_2)\cdots(1+r_n)-1=\prod_{i=1}^n(1+r_i)-1
$$

连续投资$n$期，如果假设每一期的收益率都是$\bar{r}$，该收益率为投资$n$期的**平均收益率**，满足如下关系

$$
R_n=\underset{n}{\underbrace{(1+\bar{r})(1+\bar{r})\cdots(1+\bar{r})}}-1=(1+\bar{r})^n-1
$$

那么**平均收益率**$\bar{r}$的计算公式为

$$
\bar{r}=\sqrt[n]{1+R_n}-1=\sqrt[n]{\prod_{i=1}^n(1+r_i)}-1
$$

<!--more-->

对于第$i$期的投入资金$x_i$，如果折现到第$1$期，相当于在第$1$期投资的金额$\tilde{x}_i$为

$$
\tilde{x}_i=\dfrac{x_i}{1+R_{i-1}}=\dfrac{x_i}{\prod_{k=1}^i(1+r_{k-1})}
$$

这里$\tilde{x}_1=x_1$，即$R_0=r_0=0$。根据$r_i$的计算公式，可以得知

$$
\begin{aligned}
y_i&=(1+r_i)x_i+(1+r_i)y_{i-1}\\
&=(1+r_i)x_i+(1+r_i)[(1+r_{i-1})x_{i-1}+(1+r_{i-1})y_{i-2}]\\
&=(1+r_i)x_i+(1+r_i)(1+r_{i-1})x_{i-1}+\cdots+(1+r_i)\cdots(1+r_1)x_1\\
&=(1+r_i)\cdots(1+r_1)\cdot\\
&\qquad\left[\dfrac{x_i}{(1+r_{i-1})\cdots(1+r_1)}+\dfrac{x_{i-1}}{(1+r_{i-2})\cdots(1+r_1)}+\cdots+x_1\right]\\
&=(1+R_i)\sum_{k=1}^i\tilde{x}_k
\end{aligned}
$$

当$i=n$时

$$
R_n=\dfrac{y_n-\sum_{k=1}^n\tilde{x}_k}{\sum_{k=1}^n\tilde{x}_k}
$$

由此可知，对于$n$期连续投资$x_1,\,x_2,\,\cdots,\,x_n$，其**总收益率**就是把这$n$期投资看成一个整体，把不同时期的投资折现到第$1$期，即$\tilde{x}_1,\,\tilde{x}_2,\,\cdots,\,\tilde{x}_n$，然后以此总规模$\sum_{k=1}^n\tilde{x}_k$投资，并最终资金为$y_n$时的收益率，该收益率与通过每一期收益率计算出来的总收益率是一致的。

# 2 一个例子

假设小明参与了一个投资，第一年投了1万元，年末账上资金为1.5万元，第二年又追投了1万元，年末账上资金为2万元，第三年又追投了1万元，年末账上资金为2.7万元，那么请问这3年的累积收益率是多少？

**第一种算法**：根据当期收益率来计算

第一年的当期收益率$r_1$为

$$
r_1=\dfrac{1.5-1}{1}\times 100\%=50\%
$$

第二年的当期收益率$r_2$为

$$
r_2=\dfrac{2-(1.5+1)}{1.5+1}\times 100\%=-20\%
$$

第三年的当期收益率$r_3$为

$$
r_3=\dfrac{2.7-(2+1)}{2+1}\times 100\%=-10\%
$$

所以，3期**总收益率**为

$$
R_3=(1+r_1)(1+r_2)(1+r_3)-1=(1+0.5)(1-0.2)(1-0.1)-1=8\%
$$

从以上结果上看似乎有些反直观，小明总共是投了3万元，但最后账户上只剩下了2.7万元，直观上看是亏损了0.3万元，但是算出来的**总收益率**却是正的，表明投资是盈利了。这种矛盾如何解释？且看第二种算法。

**第二种算法**：根据贴现率来计算

第一年投资的贴现值$\tilde{x}_1$为

$$
\tilde{x}_1=x_1=1
$$

第二年投资的贴现值$\tilde{x}_2$为

$$
\tilde{x}_2=\dfrac{x_2}{1+r_1}=\dfrac{1}{1+0.5}=0.667
$$

第三年投资的贴现值$\tilde{x}_3$为

$$
\tilde{x}_3=\dfrac{x_3}{(1+r_1)(1+r_2)}=\dfrac{1}{(1+0.5)(1-0.2)}=0.833
$$

所以，按照贴现值来算，3期总投资为

$$
\tilde{x}_1+\tilde{x}_2+\tilde{x}_3=1+0.667+0.833=2.5
$$

那么3期**总收益率**为

$$
R_3=\dfrac{y_3-(\tilde{x}_1+\tilde{x}_2+\tilde{x}_3)}{\tilde{x}_1+\tilde{x}_2+\tilde{x}_3}=\dfrac{2.7-2.5}{2.5}=8\%
$$

也就是说，按照贴现率来计算，小明的总投资是2.5万元（贴现到第1期），而不是表观上看到的3万元（考虑到不同时间上的投资同样的资金价值不同，因此不同时间上的投资不能直接进行加和），而到第3期期末账上的资金为2.7万元，那么**总收益率**就是正的。由此可见，**总收益率**是考虑了时间的价值后得到的结果，而不是按照如下方式计算的结果

$$
R_3\ne\dfrac{y_3-(x_1+x_2+x_3)}{x_1+x_2+x_3}=\dfrac{2.7-3}{3}=-10\%
$$

